# Generated by Django 4.0.5 on 2022-06-12 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=50), blank=True, default=list, size=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
