# Generated by Django 4.0.5 on 2022-06-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_remove_user_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
