# Generated by Django 4.0.5 on 2022-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/1160/1160283.png'),
        ),
    ]
