# Generated by Django 4.0.5 on 2022-06-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_categories'),
        ('jwt_auth', '0006_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(related_name='users_favourited', to='posts.post'),
        ),
    ]
