# Generated by Django 4.0.5 on 2022-06-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_owner'),
        ('jwt_auth', '0007_user_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(related_name='favourited_by', to='posts.post'),
        ),
    ]
